export const GET_PAGE_TRANSITION = 'GET_PAGE_TRANSITION'
export const SET_PAGE_TRANSITION = 'SET_PAGE_TRANSITION'
export const GET_LOADING_STATUS = 'GET_LOADING_STATUS'
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
